name: "Pollinations Issue Bot"
description: "Automatically responds to issues, handles commands, auto-labels, and estimates severity using Pollinations AI."
author: "CloudCompile"
branding:
  icon: "alert-circle"
  color: "blue"

inputs:
  model:
    description: "AI model to use"
    required: false
    default: "openai"
  referrer:
    description: "Referrer for Pollinations AI"
    required: false
    default: "prisimai.github.io"

outputs:
  ai_response:
    description: "The AI-generated comment"
  ai_label:
    description: "Label suggested by AI"

runs:
  using: "composite"
  steps:
    - name: Generate AI Response
      shell: bash
      run: |
        BODY="${{ github.event.comment.body:-${{ github.event.issue.body }}}}"
        COMMAND=$(echo "$BODY" | grep -oE "^/([a-zA-Z]+)" | head -1 | tr -d '/')
        echo "COMMAND=${COMMAND}" >> $GITHUB_ENV

        PROMPT="Command: ${COMMAND:-auto}
Issue Title: ${{ github.event.issue.title }}
Issue Body: ${{ github.event.issue.body }}
Previous Comments: $(jq -r '.comments_url' <<< '${{ toJSON(github.event) }}')
Please classify the issue as Bug, Feature, or Question, and estimate severity (Low, Medium, High)."

        ENCODED_PROMPT=$(echo "$PROMPT" | jq -sRr @uri)
        RESPONSE=$(curl -s "https://text.pollinations.ai/openai/$ENCODED_PROMPT?model=${{ inputs.model }}&referrer=${{ inputs.referrer }}")

        LABEL=$(echo "$RESPONSE" | grep -oP "(?<=LABEL: )\w+")
        SEVERITY=$(echo "$RESPONSE" | grep -oP "(?<=SEVERITY: )\w+")
        COMMENT="**Prisimai AI Response (${COMMAND:-auto}):**\n\n$RESPONSE\n\n**Labels:** $LABEL | **Severity:** $SEVERITY"

        echo "ai_response=$COMMENT" >> $GITHUB_OUTPUT
        echo "ai_label=$LABEL" >> $GITHUB_OUTPUT

    - name: Comment on Issue
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.issue.number }}
        body: ${{ steps.Generate_AI_Response.outputs.ai_response }}

    - name: Add Labels
      if: ${{ steps.Generate_AI_Response.outputs.ai_label != '' }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: ${{ steps.Generate_AI_Response.outputs.ai_label }}
