name: "Pollinations AI Issue Bot"
description: "Turns GitHub issues starting with !pollinations into pull requests using Pollinations AI"
author: "CJ Hauser"
branding:
  icon: "zap"
  color: "blue"
runs:
  using: "composite"
  steps:
    - uses: ./actions/pollinations-bot
